"""add quiz weights and manual grading fields

Revision ID: 016a8ddaf62a
Revises: 1a8b50a7a5c9
Create Date: 2026-05-09 16:19:40.923956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "016a8ddaf62a"
down_revision: Union[str, Sequence[str], None] = "1a8b50a7a5c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.add_column(
        "quiz_attempts",
        sa.Column(
            "status",
            sa.Enum(
                "in_progress", "pending_correction", "graded", name="attemptstatus"
            ),
            server_default="in_progress",
            nullable=False,
        ),
    )
    op.add_column(
        "quizzes", sa.Column("weight", sa.Float(), server_default="1.0", nullable=False)
    )
    op.add_column(
        "student_answers", sa.Column("manual_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "student_answers", sa.Column("teacher_feedback", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_answers", "teacher_feedback")
    op.drop_column("student_answers", "manual_score")
    op.drop_column("quizzes", "weight")
    op.drop_column("quiz_attempts", "status")
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("entity_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("audit_logs_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("audit_logs_pkey")),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    # ### end Alembic commands ###
